# Generated by Django 2.2.7 on 2020-01-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenure_raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.CharField(max_length=128)),
                ('groups', models.CharField(max_length=128)),
                ('created_date', models.DateField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
