# Generated by Django 2.2.7 on 2020-01-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenure_raw',
            name='groups',
        ),
        migrations.AddField(
            model_name='tenure_raw',
            name='group',
            field=models.CharField(default='', max_length=128),
        ),
    ]
